# Generated by Django 2.1.3 on 2018-11-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usermessage',
            fields=[
                ('id', models.IntegerField(db_column='Fld', default=10001, primary_key=True, serialize=False)),
                ('studend_name', models.CharField(max_length=50, verbose_name='姓名')),
                ('studend_email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('studend_address', models.CharField(max_length=100, verbose_name='地址信息')),
                ('studend_phone', models.CharField(max_length=20, verbose_name='电话')),
            ],
            options={
                'verbose_name': '用户留言信息',
            },
        ),
    ]
